<a href="https://colab.research.google.com/github/neerajthandayan/Misc./blob/main/Lab4/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# My Recommender

## Data Retrieval & Preprocessing

In [1]:
# Importing Libraries

import zipfile
import pandas as pd
import numpy as np
import scipy

In [2]:
# Fetching data files
!wget 'http://eigentaste.berkeley.edu/dataset/jester_dataset_1_1.zip'


# Unzipping Data
with zipfile.ZipFile(f'jester_dataset_1_1.zip',"r") as zip_ref:
  zip_ref.extractall()

--2021-04-14 02:21:18--  http://eigentaste.berkeley.edu/dataset/jester_dataset_1_1.zip
Resolving eigentaste.berkeley.edu (eigentaste.berkeley.edu)... 128.32.192.72
Connecting to eigentaste.berkeley.edu (eigentaste.berkeley.edu)|128.32.192.72|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4171628 (4.0M) [application/zip]
Saving to: ‘jester_dataset_1_1.zip.1’

jester_dataset_1_1. 100%[===================>]   3.98M  24.0MB/s    in 0.2s

2021-04-14 02:21:18 (24.0 MB/s) - ‘jester_dataset_1_1.zip.1’ saved [4171628/4171628]

In [3]:
# Creating DataFrame

data = pd.read_excel('/content/jester-data-1.xls', header=None, na_values=99)
data.drop(columns=0, inplace=True)
data.head(5)

    1     2     3     4     5     6    ...   95    96    97    98    99    100
0 -7.82  8.79 -9.66 -8.16 -7.52 -8.50  ...   NaN   NaN -5.63   NaN   NaN   NaN
1  4.08 -0.29  6.36  4.37 -2.38 -9.66  ... -0.19 -2.14  3.06  0.34 -4.32  1.07
2   NaN   NaN   NaN   NaN  9.03  9.27  ...   NaN   NaN   NaN   NaN   NaN   NaN
3   NaN  8.35   NaN   NaN  1.80  8.16  ...   NaN   NaN   NaN   NaN   NaN   NaN
4  8.50  4.61 -4.17 -5.39  1.36  1.60  ...  5.73  1.55  3.11  6.55  1.80  1.60

[5 rows x 100 columns]

In [5]:
# Finding Average Rating for Jokes

score = []
for i in data.columns:
  score.append(np.nanmean(data.loc[:,i]))

#### Best & Worst Jokes

In [6]:
# Finding Best and Worst Jokes

rdict = {'JokeID':data.columns, 'Avg_Rating':score}
rating = pd.DataFrame.from_dict(rdict)
rating.sort_values(by='Avg_Rating', ascending=False, inplace=True)
print(f'Best Joke:\n {rating.head(1)}')
print(f'Worst Joke:\n {rating.tail(1)}')

Best Joke:
     JokeID  Avg_Rating
49      50    3.665085
Worst Joke:
     JokeID  Avg_Rating
57      58    -3.83388

In [8]:
# Creating np.array object of data

arr = data.values
arr

array([[-7.82,  8.79, -9.66, ...,   nan,   nan,   nan],
       [ 4.08, -0.29,  6.36, ...,  0.34, -4.32,  1.07],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       ...,
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [ 2.43,  2.67, -3.98, ...,   nan,   nan,   nan]])

#### Helper Function Setup and Data Preparation

In [9]:
# Helper Function Setup


def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with np.NaN's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=np.NaN)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [10]:
new_arr, idx = replace(arr, 0.1)

## Latent Factor Models for Collaborative Filtering